### ISSUE TITLE
Allow port 0 listen

### ISSUE THREAD

**Issue by apla** [muit/serveMe#4]
When port 0 is used, http server will connect any available port. This is very useful for testing purposes.

Example:

```javascript
serveMe.start(0, function() {
	// shortcut will be great
	var port = serveMe.server.server.address().port;
	// write to the configuration and launch test
	// ...
});
```

Now I need to pass port number as a string, like this: `serveMe.start("0", function() {`

**Comment by apla** [comment]
Additionally, wrong port reported using such configuration:

```
>> ServeMe v0.8.2
----------
>> Listening at port:   0
>> Secure mode(https) disabled
>> Debug mode         disabled
```

**Comment by muit** [comment]
First of all thanks form your Issue. Its always a pleasure to see people use something you did.

If I understood your problem, you are sending a string instead of an integer to ServeMe. This is not currently handled (will fix it now).

For now you can do this:
```serveMe.start(0, function() {```
or if you need the port from a string:
```serveMe.start(parseInt("0"), function() {```

>"When port 0 is used, http server will connect any available port."

Im sure it would be an usefull feature but couldn´t find anything similar to it. Could you link me an example? 
In my case when it comes to debuging I usually use 3000, 9000 or similar ports.

Hope it helped.

PD:
```var port = serveMe.server.server.address().port;``` is similar to: ```serveMe.port```

**Comment by apla** [comment]
Thank you!

Use case: sometimes I need to run multiple similar servers with the same configuration on the same local CI server. I don't want to resolve port conflicts, nor define static ports for each server. Dynamic ports really helps.

**Comment by muit** [comment]
Well if you want to listen multiple ports, you can run multiple servers. ServeMe as any other node server works directly over the node API, and it doesnt support that yet (if im not brong).
